"""Defensive Prior Art search — generates links and references.

MVP approach: construct useful search URLs for Google Patents and arXiv.
Full scraping/API integration can be added later.
"""

import logging
import urllib.parse

from .models import PriorArtRef

logger = logging.getLogger(__name__)


def generate_prior_art_links(
    patent_title: str,
    claims_text: str = "",
    abstract_text: str = "",
) -> list[PriorArtRef]:
    """Generate prior art search links for a flagged patent.

    Returns direct search URLs for Google Patents and arXiv.
    """
    refs: list[PriorArtRef] = []

    # Extract key terms from title + abstract for search
    search_text = patent_title
    if abstract_text:
        search_text += " " + abstract_text[:200]

    # Clean up for URL encoding
    search_terms = " ".join(search_text.split()[:15])

    # Google Patents search
    gp_query = urllib.parse.quote_plus(search_terms)
    refs.append(PriorArtRef(
        source="Google Patents",
        title=f"Search: {search_terms[:80]}",
        url=f"https://patents.google.com/?q={gp_query}&oq={gp_query}",
        relevance_note="Search Google Patents for prior art predating this filing.",
    ))

    # Google Scholar search
    gs_query = urllib.parse.quote_plus(search_terms)
    refs.append(PriorArtRef(
        source="Google Scholar",
        title=f"Scholar search: {search_terms[:80]}",
        url=f"https://scholar.google.com/scholar?q={gs_query}",
        relevance_note="Search academic publications for prior art.",
    ))

    # arXiv search
    arxiv_query = urllib.parse.quote_plus(search_terms)
    refs.append(PriorArtRef(
        source="arXiv",
        title=f"arXiv search: {search_terms[:80]}",
        url=f"https://arxiv.org/search/?query={arxiv_query}&searchtype=all",
        relevance_note="Search arXiv preprints for prior art in CS/engineering.",
    ))

    # USPTO full-text search
    uspto_query = urllib.parse.quote_plus(patent_title)
    refs.append(PriorArtRef(
        source="USPTO",
        title=f"USPTO search: {patent_title[:80]}",
        url=f"https://ppubs.uspto.gov/pubwebapp/external.html?q={uspto_query}",
        relevance_note="Search USPTO full-text patent database.",
    ))

    # GitHub code search (for software patents)
    gh_query = urllib.parse.quote_plus(" ".join(search_terms.split()[:8]))
    refs.append(PriorArtRef(
        source="GitHub",
        title=f"GitHub search: {search_terms[:60]}",
        url=f"https://github.com/search?q={gh_query}&type=repositories",
        relevance_note="Search public repositories for open-source prior art.",
    ))

    return refs


def generate_defense_package(
    patent_title: str,
    patent_number: str,
    claims_text: str,
    abstract_text: str,
    prior_art_refs: list[PriorArtRef],
) -> dict:
    """Generate a downloadable defense package summary."""
    return {
        "patent_number": patent_number,
        "patent_title": patent_title,
        "prior_art_refs": [
            {
                "source": r.source,
                "title": r.title,
                "url": r.url,
                "relevance_note": r.relevance_note,
            }
            for r in prior_art_refs
        ],
        "response_template": _demand_letter_template(patent_number, patent_title),
        "disclaimer": (
            "This package is generated automatically and does not constitute legal advice. "
            "Consult a patent attorney for formal legal proceedings. "
            "Generated by the Patent Troll Defense System — a public utility "
            "(provisional patent application #64/020,008)."
        ),
    }


def _demand_letter_template(patent_number: str, patent_title: str) -> str:
    return f"""TEMPLATE RESPONSE TO PATENT DEMAND LETTER
=========================================

[Your Name]
[Your Address]
[Date]

To Whom It May Concern:

I am writing in response to your correspondence dated [DATE] regarding patent
{patent_number} ("{patent_title}").

After careful review, I believe the claims asserted against my [product/invention]
are without merit for the following reasons:

1. PRIOR ART: The concepts described in the asserted claims were publicly disclosed
   prior to the patent's effective filing date. See attached prior art references.

2. CLAIM BREADTH: The asserted claims are drafted with overly broad language that
   fails to meet the enablement and written description requirements of 35 U.S.C. §112.

3. OBVIOUSNESS: The claimed invention represents an obvious combination of known
   elements under 35 U.S.C. §103. See attached prior art analysis.

I respectfully request that you withdraw your demand. I reserve all rights and
remedies available to me, including but not limited to seeking a declaratory judgment
of non-infringement and invalidity, and recovery of attorneys' fees under
35 U.S.C. §285 if this matter proceeds to litigation.

Sincerely,
[Your Name]

---
Note: This template is provided as a starting point only. It does not constitute
legal advice. Consider consulting a patent attorney, particularly for matters
involving potential litigation. Many patent attorneys offer free initial consultations.

Generated by the Patent Troll Defense System
Public utility — provisional patent #64/020,008
"""
