baseURL = "https://jonnywren.netlify.app/"
languageCode = "en-us"
title = "Seattle Wren"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
